language: python
python:
- 2.7
- 3.4
sudo: false
install:
- if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh
  -O miniconda.sh; else wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
  -O miniconda.sh; fi
- bash miniconda.sh -b -p $HOME/miniconda
- export PATH="$HOME/miniconda/bin:$PATH"
- hash -r
- conda config --set always_yes yes --set changeps1 no
- conda update -q conda
- conda info -a
- conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION pandas mock pytest
- source activate test-environment
- python setup.py install
script:
- python setup.py test
deploy:
  provider: pypi
  server: https://upload.pypi.io/legacy/
  on:
    tags: true
    all_branches: true
    python: 3.5
  user: jaraco
  password:
    secure: T2rPlwunGoVUW2eWnN46GtzrNchTE3EMKfwlZb3TWBC5vBIQSQJXK518Mo92NeUaMsTBoEjvGyUnnUxCfnadKNRT/2OMFiLG2FqhNhcw/Bb2DyRdZ6GCtd7ScrAwTGSRwyDttKyutA5r/6ac+aZTWie+WPtTsGjvEShNtyN4ECo=
  distributions: release
